# Generated by Django 3.2.6 on 2021-08-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='side',
            name='price',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='price',
            field=models.IntegerField(default=8),
        ),
    ]
