# Generated by Django 3.2.6 on 2021-08-31 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210831_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isVegan', models.BooleanField(default=False)),
                ('isVegetarian', models.BooleanField(default=False)),
                ('total', models.IntegerField(default=0)),
                ('sides', models.ManyToManyField(to='main_app.Side')),
                ('sushi', models.ManyToManyField(to='main_app.Sushi')),
            ],
        ),
    ]
