# Generated by Django 3.2.6 on 2021-08-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sushi',
            name='sides',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
