# Generated by Django 3.2.6 on 2021-08-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210831_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sushi',
            name='sides',
            field=models.ManyToManyField(to='main_app.Side'),
        ),
        migrations.AlterField(
            model_name='sushi',
            name='description',
            field=models.TextField(default='comes with free soy sauce, ginger, and wasabi paste', max_length=250),
        ),
    ]
